### ISSUE TITLE
RFP: ShockCmd

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#100]
**Name of Outgoing Message, if any:**

ShockCmd

**Message Fields:**

* _Id_ (unsigned int): Message Id
* _DeviceIndex_ (unsigned int): Index of device
* _Shocks_ (array): Shock strength/duration
  * _Index_ (unsigned int): Index of shocking element
  * _Strength_ (double): Shock strength with a range of [0.0-1.0]
  * _Duration_ (unsigned int): Duration of shock, in milliseconds.

**Describe message usage scenario**
To be used for shock collars and estim/tens units. Issues a single, static power level output for a certain amount of time.

**Additional context**
This is mainly aimed at shock collars, but could be used for TENS/Estim also. For pattern based systems like a TENS unit, it may be possible to let the user denote a pattern to use that has shock-like start?

**Comment by blackspherefollower** [comment]
Index of rotation motor?

Is shock going to be the baseline estim command? Thinking LiBo Elle/Whale: the estim is mapped to a vibration level, but could just as easily be moved to shock. Especially if duration were optional, or 0 were used for infinite duration.

**Comment by qdot** [comment]
Hmm. That's actually a pretty good point. Maybe it's worth calling this "EstimCmd" instead of "ShockCmd"? Like, it's really had to define the... textures? Contexts? of different types of estim, but this message could be useful across collars, boxes like the et-312, and toys like the Whale/Elle.

Also: Do you think we should say this message has a maximum time? Like 1 second? I'm just wondering if we should use something like collars do, where it requires multiple pulses (or in our case, messages) to make one long pulse.

**Comment by qdot** [comment]
@blackspherefollower I'm a little iffy on "duration" here. Since the context of this command is "Shock" and not "Estim", I'm considering maybe removing "duration" as an argument, adding it as a message attribute to denote how long it will run for (probably never over 500ms), and requiring this to be called repeatedly to keep the stimulation level going, similar to how collar firmwares work. There's a ton of ways this could be subverted (especially once we get "DelayedDeviceCmd" send in arrays), but it still feels safer. Thoughts?

**Comment by blackspherefollower** [comment]
That sounds fair. Although I do like the other proposal of having a max time, just in case 500ms is too long.

**Comment by qdot** [comment]
I suppose there could be a "why not both" argument here, since we'd want sane defaults on things like shock collars. 

I'm also tempted to split this message and make both a "ShockCmd" and an "EstimLevelCmd", so we can split contexts between the Pavlok/Shock Collars and ET312/PipiJing Whale/etc...

**Comment by blackspherefollower** [comment]
I didn't expect you to reply so quickly. I edited my comment above.

**Comment by blackspherefollower** [comment]
My understanding was the shying away from implementing any estim commands (other than the safety aspects) was that the ET312 and a basic TENS unit only have intensity in common, the real estim unit has way way more capabilities. Although I guess the message could have a bunch of optional parameters that are described as needed or not via MessageAttributes

**Comment by qdot** [comment]
Yeah I honestly think we'll end up at the waveform idea for most estim, which is why I'm a little iffy combining it all under this "correction" type message.

**Comment by qdot** [comment]
Gonna call this too risky at this point, WONTFIX.
