### ISSUE TITLE
Intiface can't find Lovense Max2

### ISSUE THREAD

**Issue by Ink0gn1to** [buttplugio/buttplug#117]
I connected Max2 through BT4 usb adapter to my PC on Win10. An indicator on the device shows a successful connection.
Starting server in Intiface, connect to it with ScriptPlayer, and start scaning.
But nothing happens, I guess scaning have no results. What's wrong?

**Comment by blackspherefollower** [comment]
@Ink0gn1to if the indicator light on the Max turned on before you connected scriptplayer to Intiface, then something else connected first.

This is very unlikely to be a bug. You might want to ask for help over in the tech support Discord channel instead: https://discord.gg/cUxz3d7

**Comment by Ink0gn1to** [comment]
No, when I Max turn on the indicator flashes. I click on tray BT icon and connect to LVS-*** device. The indicator lights up constantly. I tried not to do this, but the result is the same: scanning have no results.

**Comment by blackspherefollower** [comment]
Again, this is not the place for tech support. Let's continue this on Discord.
