### ISSUE TITLE
Support for Magic Motion (different Manufacturer)

### ISSUE THREAD

**Issue by WinSys323** [buttplugio/buttplug#166]
Please add support for Magic Motion devices. I'm not talking about Magic Motion this plugin already supports. Instead I talk about this manufacturer:

`https://www.magic-motion.de/masturbationsmaschinen/25/magic-motion-sensation-edition-mit-mc/rc-controller?c=14` controlled by an MC/RC Controller
and
`https://www.magic-motion.de/masturbationsmaschinen/111/magic-motion-handmaid-cyber?c=14` controlled by `Cyberfun` mobile app or computer software. I believe its bluetooth.

**Comment by qdot** [comment]
@blackspherefollower Did you ever manage to source these?

**Comment by blackspherefollower** [comment]
@qdot no... I considered renting one, but import/export is a mess right now so I'm afraid it'd have to be returned before it was delivered...
