### ISSUE TITLE
Allow users to rename devices, based on their address

### ISSUE THREAD

**Issue by lucky-skebe** [buttplugio/buttplug#168]
Hi I wanted to ask if there is anyway to identify a Device via the C# api other than by name.

For Example if I connect 2 Lovense Hush is there any way to distinguish those?

Preferably stable even through Client and/or Server Restarts?

Background:

I would like to be able to save currently selected devices and restore the ones that get found the next time my aplication starts and connects to the buttplug server.

**Comment by qdot** [comment]
This is now partially implemented in #208, still need to figure out cross session persistence.

**Comment by qdot** [comment]
Done in v6, will close when pushed to master.
