### ISSUE TITLE
Add LiBo Whale Battery reading functionality

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#177]
Code is done but we don't have a battery status message yet. cc @bnm12

```csharp
private int getBatteryLevel()
{
            throw new NotImplementedException("While most of this method is done it still needs to be adjusted/completed - see the comments");
            int batteryLevel = Convert.ToInt32(0x64 /* 100 in hex */);  // Read from Info.Services[1] + Info.Characteristics[uint)LiBoBluetoothInfo.Chrs.Rx] here
            return batteryLevel;                                        // As far as I can tell we currently have no way of reading values
}
```

**Comment by qdot** [comment]
@blackspherefollower Do we still wanna do this? I know we still have the elle in the protocol list.

**Comment by blackspherefollower** [comment]
Urr... I guess most devices have battery readings that I've totally ignored...

I think maybe we should just add it to "the great sensor adding" that I'll do once we've got sensor stuff turned up and I go through all my boxes?

**Comment by qdot** [comment]
Sounds good. I'm gonna close this and will add a larger sensor update issue.
