### ISSUE TITLE
WeVibe protocol does not exercise full range of toy power

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#194]
**Describe the bug**
See https://github.com/buttplugio/buttplug-csharp/pull/670. Need to port this to the rust library.

**Comment by qdot** [comment]
@blackspherefollower Since you're basically taking care of protocols now, can you take a look at this and see if it's valid?

**Comment by blackspherefollower** [comment]
I think it might have been addressed, but I'll need to do more testing. I know I take the max speed-3 from the WeVibe device configs, but there was also a byte position difference noticed.

I've actually got a Chorus in the post, so I should be able to some extra comparisons next week.

**Comment by blackspherefollower** [comment]
Well, I can confirm that we got the byte order set correctly,
And the speeds check out (although I'm no longer convinced that speeds 1 and 2 are invalid).

**Comment by blackspherefollower** [comment]
However, I cant get my Chrous to pair with my Windows box, so it's back in that "if you can pair it, it'll work" holding pattern.

**Comment by qdot** [comment]
We figured out the pairing thing via CSR radios, and apparently the protocol works, so closing this for now.
