### ISSUE TITLE
Should BLE Battery services/characteristics be autodetected in the BTLEPlug manager?

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#198]
BLE Battery service/characteristics are standardized, so we can just detect whether they exist on connect. Usually we require explicit definition in the device config for endpoint names and what not, but this seems like a case where we could just look on every connect and use what we get?

**Comment by blackspherefollower** [comment]
How about looking for this automatically on all BLE devices, but making it overridable since so many devices have their own ways of reporting battery level within their custom protocols?

**Comment by qdot** [comment]
Just closing this as invalid. The comment from 3 years ago is right: Too much possible variability in battery readout.
