### ISSUE TITLE
Mysteryvibe Tenuto doesn't connect correctly

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#210]
While the Crescendo seems to connect and control fine through both desktop and WASM, the Mysteryvibe Tenuto dies on connect, possibly due to protocol differences. Need to go look at the MV firmware updates and protocol changes, see if there's a smarter way to do this.

**Comment by blackspherefollower** [comment]
Testing with v48/5.1.7 using a CSR4 dongle, my Tenuto (fw1.2) is responding (it requested to pair with the OS and once done seemed fine).

There is a firmware upgrade pending, but I'm struggling to get it to upgrade

**Comment by qdot** [comment]
I think this has worked for a while now, closing until we get any new reports on the Tenuto.
