### ISSUE TITLE
RFP: OscillateCmd - For non-positional linear hardware

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug#338]
**Name of Outgoing Message, if any:**
OscillateCmd 

**Message Fields:**
* Speeds: Array of oscillation speeds
  * Index: Number (index of oscillator, in case devices with multiple oscillators turn up)
  * Speed: Number representing speed (if double, percentage of max speed, if integer, the specific speed step)
  * Reverse: Boolean (optional) - At least one device has a concept of direction, but (anti)clockwise isn't a good way to describe changing the direction of a linear movement.

**Describe message usage scenario**
There's a growing number of rotation to linear actuator based devices getting Bluetooth support.
Many of the thrusting frame based devices use large wheels connected to a linear piston to achieve this, but other designs include rotating cuff jigs (SayberX for example).

These devices have no concept of position, just speed, so the current LinearCmd doesn't map well. In fact the MotorBunny Buck is the only such device known to have direction in addition to speed, so for most devices RotateCmd doesn't work either.

The command actually looks almost identical to VibrateCmd right now, but mapping linear motion to vibration commands seems wrong.

**Comment by qdot** [comment]
Duplicated by #422
