### ISSUE TITLE
Support for Vorze A10 Piston SA does not appear to be fully functional

### ISSUE THREAD

**Issue by symidewafa** [buttplugio/buttplug#348]
It appears from `buttplug-device-config.yml` that the Vorze A10 Piston SA is intended to be supported, so I'm submitting this as a bug:

https://github.com/buttplugio/buttplug/blob/73146d15f86804916e2ee93308c9d241d3ea91fd/buttplug/buttplug-device-config/buttplug-device-config.yml#L1312-L1318

**Describe the bug**

Buttplug is able to connect to the device successfully (the device itself indicates via its LED that it's connected), but does not appear to be able to properly set the device in motion.

**Expected behavior**
Using Buttplug Playground, the Start Oscillation button should cause the device to start moving.

**Actual behavior**
The device does not move at all.

**Additional context**
[amateras977/A10ServerBLE](https://github.com/amateras977/A10ServerBLE) is able to control the device, so both the device itself as well as the BTLE adapter can be ruled out as potential causes.

**Comment by qdot** [comment]
Oh, oops, we shouldn't even be able to connect to it at this point I don't think. Our problem has been trying to line up movement with our system, which requires a ton of work to figure out timing. I'll at least remove connection support until we get that figured out.

**Comment by symidewafa** [comment]
Ah, that's a bummer. Am I understanding correctly that buttplugio/stpihkal#87 is the blocking issue here? Is that something I or others can help with?

**Comment by blackspherefollower** [comment]
The blocking issue is that the timings are still somewhat unknown: the device takes a position and a speed, but since buttplug will get position and a time period the speed of the device over various distances needs to be mapped out and turned into a mathematical formula.

**Comment by Nootna8** [comment]
Actually got this device working yesterday using the speed calculation from the launch helper.

But like already mentioned, a new speed function will need to be made for this device since it's verry stuttery now. I'll try making a data map tonight and see how far I'll get with a formula.

**Comment by blackspherefollower** [comment]
How are you planning on measuring the time? I've got a half finished audio based tool that I almost got working (except that on a single movement the piston does this little jerk once it's reached it's target position that threw off my results, plus my microphone turned out to not be up to the job)

**Comment by electromuis** [comment]
Was thinking to just use a stopwatch app haha. But recording audio sounds like a good idea! I have a great microphone, perhaps I can run your tool? Audio can also be filtered with audacity before analyzing.

I could also connect a limit switch via arduino but feels like a lot of extra work which might not make a difference.

**Comment by Nootna8** [comment]
Was thinking to just use a stopwatch app haha. But recording audio sounds like a good idea! I have a great microphone, perhaps I can run your tool? Audio can also be filtered with audacity before analyzing.

I could also connect a limit switch via arduino but feels like a lot of extra work which might not make a difference.

**Comment by blackspherefollower** [comment]
From my notes, the position range is 0-200, the speed range is 20-60 and the forward and reverse speeds differ.
I've just ported my tool to use buttplug-rs (which is going to make it so much more maintainable), but my piston isn't powering on (not sure if it's even charging) so I don't know if it's actually going to work... Either way, I've pushed it to https://github.com/blackspherefollower/AudioTimer

**Comment by blackspherefollower** [comment]
HAH! The moulding of the interchangeable plug socket was insulating the pin, so apparently I've NEVER charged my piston...

**Comment by Nootna8** [comment]
That's hilarious. According to the vorze docs speed is 0-100, or do you mean only 20-60 is actually different?

**Comment by blackspherefollower** [comment]
Which docs? Take a look at buttplugio/stpihkal#87

**Comment by Nootna8** [comment]
[VORZE_SDK.pdf](https://github.com/buttplugio/buttplug/files/6748826/VORZE_SDK.pdf)

According to their docs at least

**Comment by blackspherefollower** [comment]
Wow. Hadn't seen that doc before. Cool. Could you cross post that link in the stpihkal issue please?

I think the person who reversed the protocol first, who's code we cribbed, left comments that if the speed drops too low, the device will crash. I can't remember anything about the upper limit.

**Comment by Nootna8** [comment]
Tada

**Comment by Nootna8** [comment]
[VORZE_SDK_en.pdf](https://github.com/buttplugio/buttplug/files/6750104/VORZE_SDK_en.pdf)
Found english

**Comment by Nootna8** [comment]
Audio silence detection didn't really work for me, on lower speeds the thing is just too quiet. But I do have a list of recordings per speed that can be timed with a wave viewer like Audacity, after which a formula can be constructed.

[Piston.zip](https://github.com/buttplugio/buttplug/files/6750359/Piston.zip)

In case anyone else is bored lol, includes the buttplug-rust script and the audiotimer script I used.

More to be done tomorrow :o

**Comment by qdot** [comment]
Honestly, if the fleshlight launch timing even vaguely works, we can land that now and tweak the timing in a later version, just to have something I guess? How bad is it currently?

**Comment by Nootna8** [comment]
Let's just say its rough ...

In the zip file you'll find a vorze_sa.rs. Just comment out 133-140 and uncomment 132.

Actually I don't even think it should be iterating the vectors since there's only 1 motor. Also might be nice to add a separate VorzeA10PistonCmd which I don't have right now.

**Comment by qdot** [comment]
We aren't really doing specific device commands anymore, you'd just use the Raw commands for that now.

**Comment by Nootna8** [comment]
![Timing](https://user-images.githubusercontent.com/86775993/124319242-38c72380-db7a-11eb-8626-64beeb7db746.png)

My timing results, didn't really notice a big difference between back-forth or reverse, but i'll put 2 diffrent formula's to be sure. Will send a pull request once this works for me. Maybe it could still differ for shorter ranges, only did the full 0 to 200 but should be plenty good for now.

**Comment by Nootna8** [comment]
Two directions wasn't worth the effort, never worked in rust before so feel free to cleanup code haha.

But at least for me it works pretty good!

PR Link: https://github.com/buttplugio/buttplug/pull/355

**Comment by qdot** [comment]
This is fixed and landed in v39 of the Intiface Engine. Thanks @Nootna8 and @blackspherefollower!
