### ISSUE TITLE
Vorze devices may all be able to use Write (not Write Without Response)

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#353]
Vorze devices (at least the Festa and Cyclone, more info coming on UFO/Bach when they charge) use Write characteristics, not write without response. Our Write w/o response call gets upgraded silently to a write call and then it just dumps the response. So we might be able to remove that check and turn this to just be true.

**Comment by qdot** [comment]
cc @blackspherefollower 

Bach Smart is the same deal. Write only.

I can't seem to locate the power cable for the UFO at the moment so that's a bit of an issue. :|

**Comment by blackspherefollower** [comment]
This is weird: other than he Rocket, my Vorze advertise only write but respond to both write and write-without-response.
Tested with nRF Connect which does not do fallback (as tested with the Rocket)
