### ISSUE TITLE
Calling batteryLevel while vibrating get stuck

### ISSUE THREAD

**Issue by kaciexx** [buttplugio/buttplug#390]
**Describe the bug**
Calling the batteryLevel of the Lovense Hush while the toy is vibrating will make everything stuck (can't send command to the toy). 

**Expected behavior**
Should be able to get the battery level while the toy is vibrating

**Actual behavior**
The toy is locked and it it not possible to use it anymore. It is stuck on the last vibrating level

**Additional context**
Tested with Intiface and it works correctly.

**Comment by qdot** [comment]
Should be fixed in v6.
