### ISSUE TITLE
Bluetooth device disconnect can block tasks, causing CPU spike

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#407]
**Describe the bug**
1. Connect a device using Buttplug
2. Turn off device

**Expected behavior**
No extra CPU is used.

**Actual behavior**
Thread that the device task was running on will block, consuming one CPU due to lack of yielding. Reconnecting/disconnecting enough can block the processor once all cores are saturated.

**Additional context**

Report taken from discord.

**Comment by bassknoppix** [comment]
I am the reporter.

"https://metafetish.club/t/arduino-launch-emulator-esp32/1038"

The device is running the code described in the url (though the details are different).

Each time the device is powered off and the connection is broken, "InterfaceCLI.exe" will occupy one thread.

Information on the PC where it was run
CPU:AMD Ryzen 9 5900X
RAM: 64GB
Windows:
  Edition Windows 10 Pro
  Version: 20H2
  OS Build 19042.1288
  Experience Windows Feature Experience Pack 120.2212.3920.0

**Comment by qdot** [comment]
I tried this with a Lovense device as well as an OhMiBod device and we don't seem to be getting these same issues. I'm wondering if there is some sort of shutdown issues specific to that arduino code that causes issues with our bluetooth library.

**Comment by qdot** [comment]
This somehow seems to have been fixed in the latest buttplug release, so I'm guessing the jump to btleplug v0.9 fixed it. Closing for now, will reopen if I get more reports.
