### ISSUE TITLE
Devices may be blacklisted if the name advertisment hasn't arrived yet

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug#411]
**Describe the bug**
I still have concerns about the guarding on the seen devices though: if a device has only sent manufacturer info when the matcher checks it, it'll be blacklisted before any meaningful check can be performed

**Expected behavior**
Devices with names or service advertisements should be matched, regardless of the order of advertisment packets.

**Actual behavior**
The first time a device is seen, it's either matched or blacklisted.

**Additional context**
Maybe the seen array could be a map of address Vs enum of matchable attributes: track which matchable advertisements have been tested, so if a new one arrives, we know.

**Comment by qdot** [comment]
Ok both the Keon and Handy have this issue, so we're gonna have to fix it ASAP and point release this evening. Oops. :)
