### ISSUE TITLE
Cannot reconnect when the server connection gets lost

### ISSUE THREAD

**Issue by lucky-skebe** [buttplugio/buttplug#421]
**Describe the bug**
I connect to the intiface server using the rust client (5.1.5) and websockets. When I initiate a disconnect from the client I can reconnect using the same client without any problems.
When I stop The server while the client Is connected the client seems to be in an invalid state somewhere in between because I'm unable to reconnect or manually disconnect.

**Expected behavior**
Being able to either call disconnect or connect again and establish a connection once I restart the server.

**Actual behavior**
When the server gets stopped while the client is connected further calls to the connect method fail with an error "Connector already connected, cannot be connected twice."

Manually trying to disconnect leads to the the error: "ButtplugConnectorError(ConnectorChannelClosed)".

**Additional Context**
This my current code:
https://github.com/lucky-skebe/butthesda-rs/blob/feature/remote_server/src/buttplug.rs

**Comment by qdot** [comment]
Ok so I'm realizing there... isn't really a defined behavior here. I don't think I actually meant for clients objects to be re-usable? Mostly because of the bookkeeping to make sure correct cleanup happens when a client goes down.

That said, would keeping the reusable client be helpful? Obviously we should have better state handling no matter what, but this would be a good time to explicitly say whether or not we want reconnectable clients.

**Comment by lucky-skebe** [comment]
I assumed it was supposed to work because the whole client "feels" that way with it being called client instead of connection and having explicit connect, disconnect methods.

If it can't be reused I feel like having the disconnect method being private and calling it on drop or having disconnect consume the client instead of a reference would have been the more "logical" choice? Like why would I call disconnect and keep the client when I can't do anything with it afterwards?

Also it does work when you initiate the disconnect instead of the server.

those are just my thoughts though.

At the very least I feel like it should be consistent bewteen calling disconnect and the server disconnecting.

if it can't disconnect I can just create a new client in that case (is a little bit more work but should be doable)

**Comment by qdot** [comment]
I'm starting on buttplug v6 dev now so this will be the perfect time to resolve this. I *think* having a reusable client makes sense, we'll just have to make sure the state is handled correctly on disconnect/reconnect. Most of that is owned by the task that's spun up when we call connect(), which hopefully we'll track better once #314 comes in (which is in the v6 specs).

**Comment by qdot** [comment]
Ooook, well I think I have some vague handwavey fixes for this in v6, but it's not as nice as I'd like. Basically there's a lot of status that depends on one side of an MPSC channel dying to kick off status updates in the rest of the system, and using that side effect is a bit too rube-goldberg-machiney for my tastes now. That said, my goal here is to get v6 out the door so I'm gonna take the easy fix for now and file a followup to throughly scrub this later.
