### ISSUE TITLE
Svakom Iker cannot be found with CSR4 adapters

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug#431]
**Describe the bug**
Using a CSR4 BLE adapter, the Iker isn't discovered.
The devices doesn't appear to advertise a name, so the matcher fails.

**Additional context**
* Reading the name attribute after connect, the name is actually "Iker" followed by some non-printable characters.
* Using either broadcom or realtek chipsets, we don't see the bug (I guess the drivers for those chipsets truncate the non-printable characters?)
* Using the Intel chipset, the bug reproduces, but can be rectified by changing the matcher to "Iker*"; this doesn't correct the issue with the CSR4 dongle.

**Comment by qdot** [comment]
I think this is probably worth just making a FAQ entry and calling it done?

**Comment by SirLancelot06** [comment]
Is this fixed yet or it can't be fixed?

**Comment by blackspherefollower** [comment]
@qdot Can you close this issue?
