### ISSUE TITLE
Implement DG-Lab Coyote support

### ISSUE THREAD

**Issue by shadowpanther** [buttplugio/buttplug#445]
**Feature Description**

The bluetooth protocol description could be found at https://github.com/DG-LAB-OPENSOURCE/DG-LAB-OPENSOURCE

**Comment by qdot** [comment]
Due to liability and complexity, there are no plans to support estim in Buttplug.

**Comment by shadowpanther** [comment]
There are supported estim devices though... https://iostindex.com/?filter0ButtplugSupport=4&filter1Features=OutputsEstim

**Comment by qdot** [comment]
Getting IOSTIndex updated now to reflect that.
