### ISSUE TITLE
problems with build /spec when using node version newer than node 17

### ISSUE THREAD

**Issue by silverhikari** [buttplugio/buttplug#478]
**Describe the bug**
when building spec webpage with versions newer than node 17, the build will fail with
```
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'

this is caused by a change in node 17 when dealing with openssl 3
```
**Expected behavior**
the build succeed and a built dist is made in the .vue folder

**Actual behavior**
build fails and nothing is created.

**Additional context**

so far the solutions that people have recommended are adding "export NODE_OPTIONS=--openssl-legacy-provider;" before "vuepress build protocol-spec" in the package.json which is a workaround or the bug has been fixed in webpack v5.61.0

**Comment by qdot** [comment]
Ok, fixed in dev just using cross-env. Will land to master tomorrow, which is also when the new spec version becomes official.
