### ISSUE TITLE
Lovehoney Desire devices might be writing in the wrong mode

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug#487]
**Describe the bug**
A user on discord reported that a Lovehoney Desire error'ed on write on Linux: https://discord.com/channels/353303527587708932/453328145857118220/1026794016504811520

Futher investigation suggests that the device doesn't actually support "write without response", which is how buttplug writes to the device right now.

**Comment by qdot** [comment]
We haven't heard anything more about this, closing until we get more requests.
