### ISSUE TITLE
Update Oscillation ScalarCmd handling for Lovense Machine/Gravity

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#510]
**Feature Description**

Needed for the Lovense Machine as well as the Gravity, both of which use different commands to Oscillate.

**Comment by blackspherefollower** [comment]
I think this is mostly done in:
* 7f291789807dab7051bc5aec17e5f4d9189bb394
* 878e5bcaa28992151ffff061e48f333797ea9f07

Looks like the sex machine via lovense connect is all that's outstanding
