### ISSUE TITLE
Can't connect Svakom Sam Neo to Intiface, tried 3 diff BT adapters

### ISSUE THREAD

**Issue by GordonHollow** [buttplugio/buttplug#582]
When i start searching it found device, but can't connect with this error in log

Device errored while trying to connect: Device type specific error: Btleplug error: Not connected

Latest Intiface 2.4.3

It works fine on xtoys\app and site with BT adapters i have tho

**Comment by nab-os** [comment]
And to help a little bit digging out the bug, I experienced the same issue since I got my Sam Neo, 4 months ago.

**Comment by nab-os** [comment]
![image](https://github.com/buttplugio/buttplug/assets/9805355/070bd5f1-b5c6-41ae-882a-e0dd9375a83c)

**Comment by qdot** [comment]
This is a known bug, fixed in the current version of Buttplug. I just need to update Intiface Central for it. Hoping to do so within the next week.

**Comment by qdot** [comment]
This should be fixed in Intiface Central >= v2.4.4.

https://intiface.com/central
