### ISSUE TITLE
Please add support to Leten Vivi

### ISSUE THREAD

**Issue by leonardcoutinho** [buttplugio/buttplug#600]
Hi, I have an Leten Vivi, is an old vibrator but Works nicely and I like to integrate in this api.

I'm already research some data about It to work.

0000FFF1-0000-1000-8000-00805F9B34FB is the main gatt key and it use first two hex bit values to control basic vibrations(I don't know about music in app, I think it process audio in app and only send the processed commands to device), like 01 01 or 01 0f
the identifier of mine is F520B-LT.

I use nRF to connect and works, first I sent to 0xFFF1(0000FFF1-0000-1000-8000-00805F9B34FB) UUID an FFFF value to clear values, then 0401(maybe to initiate device, I don't know but without the device don't vibrate), then 0300(or other like 0100) and then vibrator works. After this I can use first byte 01, 02, 03, 05 to change modes, and second to change variations, no need to sent other command or authenticate in vibrator. I saw in bluetooth logs that app send FFFF value to stop device, and when I enter in screen mode it send the correct value to mode or intensity. I don't investigate yet about values of modes and intensity but is easy to document this.

**Comment by leonardcoutinho** [comment]
[btsnoop_hci.log](https://github.com/buttplugio/buttplug/files/13655971/btsnoop_hci.log)

**Comment by leonardcoutinho** [comment]
values from 03 00 to 03 06 are to vibraton intensity. 01 00 to 01 0F are to builtin presets. 02 00 to 02 28 are some vibration intensity too, but more granulated. Maybe 05 has something too but I can't investigate now. 04 01 is only to initate, I can't use to make device vibrate, 05 make, and 06 and up don't do nothing to.

**Comment by leonardcoutinho** [comment]
[btsnoop_hci.log](https://github.com/buttplugio/buttplug/files/13668277/btsnoop_hci.log)
bluetooth log with app startup and pairing process

**Comment by qdot** [comment]
cc @blackspherefollower, not sure if you're interested in this.

**Comment by blackspherefollower** [comment]
I actually think c447b78ac073947ada42049d59e0bb59df7a08f8 closed this

**Comment by qdot** [comment]
Marking done.
