### ISSUE TITLE
FeatureOrder in device config isn't doing anything

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#620]
Filing this specifically to ask @blackspherefollower:

I'm rebuilding the config formats right now, and just ran into FeatureOrder. We still have it for 3 *very* rare toys that have FeatureOrder in their config, but the field is never read or stored anywhere on config load. Obviously it's dead or at least hasn't affected anything, but do we need it going forward?

**Comment by blackspherefollower** [comment]
I'm pretty sure that feature description and type replaced any need.

**Comment by qdot** [comment]
Ok, gone in the new config.
