### ISSUE TITLE
JoyHub Mariner Support

### ISSUE THREAD

**Issue by Bobafet231** [buttplugio/buttplug#633]
**Feature Description**

Would it be possible for someone to add the support of the Mariner device from JoyHub (J-Mariner) that has succion and rotation ? and its bluetooth

**Comment by blackspherefollower** [comment]
@Bobafet231 Do you have a link to the device?

**Comment by Bobafet231** [comment]
@blackspherefollower this is where i bought it https://www.amazon.fr/Masturbeuse-Masturbateurs-daspiration-Masturbateur-Automatique/dp/B09QG58SML/ref=sr_1_8?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=3I7SGJP40NR48&dib=eyJ2IjoiMSJ9.D9wJ6iGz8lcBQk6uDvaOr7swHmHOdjfNJ7AVejAMlGiB2jKsfrmNyvJOxN8HiFS2lOsZsvBDLr2wjhR8IXLvnne7G85r6QyVtu8l1voMITTlLgwHPzOu82aTVgxeuSSL3OtA0ZSSjbFdLflhh2z1SNJy0lLhuhx1iwuKLW5_nbcxxYzIqRoH2PzUw3P9yHWjG_t1Rg5uUm6FWEF8mYFPSzwKTNNCWKXrNyXs1LRtmBmF9SczreWGQpnghiCxMYrbFOOVQ-9RfDZd8c-fzAi1mWRbisM_Q8OOcqmDXbLqhwU.z-lySx1bcDYN_tshnlEGAMCE1tRjObbkwwK4j2lj0pU&dib_tag=se&keywords=sextoy+homme&qid=1713965675&sprefix=sextoy+homme%2Caps%2C65&sr=8-8

**Comment by Bobafet231** [comment]
its not rly documented, on amazon there isnt even any mention of any sort of app but once i got it i got a little notice explaining how to connect it to JoyHub

**Comment by blackspherefollower** [comment]
The JoyHub devices are often not advertised as such: it makes them hard to find.

I'll write up steps for testing which variant of the protocol this device uses tomorrow.

**Comment by Bobafet231** [comment]
okay thanks @blackspherefollower you can ask me some technical thing if you want i have some coding skills (some)

**Comment by Bobafet231** [comment]
@blackspherefollower am ready to test the protocol variant if you want i only need to go in a few hours

**Comment by NickPoole** [comment]
Good timing, I'm just about done with my dayjob stuff for today.

On your phone, install "nRF Connect": this will let you scan for BT4 devices, connect and send and receive data on their characteristics.
Scan for the Mariner and hit connect.
Find and select the 0xffa0 service and you should see the Characteristic 0xffa1; they'll be a little up arrow icon on the right on the characteristic to open the send packet dialog

So I'll need you to send:
 * a003ff000000aa 
 * a00300ff0000aa 
 * a0030000ff00aa 
 * a00300000000aa 
and tell me what happens after you send each one

**Comment by Bobafet231** [comment]
ah yeah i already have it installed
il do it now

**Comment by blackspherefollower** [comment]
Good timing, I'm just about done with my dayjob stuff for today.

On your phone, install "nRF Connect": this will let you scan for BT4 devices, connect and send and receive data on their characteristics.
Scan for the Mariner and hit connect.
Find and select the 0xffa0 service and you should see the Characteristic 0xffa1; they'll be a little up arrow icon on the right on the characteristic to open the send packet dialog

So I'll need you to send:

    a003ff000000aa
    a00300ff0000aa
    a0030000ff00aa
    a00300000000aa
    and tell me what happens after you send each one

**Comment by Bobafet231** [comment]
[a003ff000000aa] -> enables rotation
[a00300ff0000aa] -> stops rotation
[a0030000ff00aa] -> does nothing
[a00300000000aa] -> does nothing

@blackspherefollower 
@NickPoole

**Comment by Bobafet231** [comment]
i sent them in the up to down order

**Comment by Bobafet231** [comment]
nothing happens for thoses 2
@blackspherefollower

**Comment by blackspherefollower** [comment]
O, lets try a007010007ff and a007000000ff

**Comment by Bobafet231** [comment]
a007010007ff -> enables succion
a007000000ff -> stops succion

**Comment by Bobafet231** [comment]
but in diy mode for rotation its a rotation speed slider and for succion its like "modes" it kinda changes the fréquency soo a007010007ff is one of the succion modes

**Comment by blackspherefollower** [comment]
Ah, so this looks like the same suction system as the vortex tongue. Do 1-3 feel constant but increasing intensity?

**Comment by Bobafet231** [comment]
not rleally the frequency is increasing

**Comment by blackspherefollower** [comment]
I think that's as close as it gets to increase intensity. At 4 does it start following some other pattern?

**Comment by Bobafet231** [comment]
https://github.com/buttplugio/buttplug/assets/168737684/93adb05a-a6cc-4053-9d4f-d808e9eb7c2b

@blackspherefollower

**Comment by Bobafet231** [comment]
i hope this helps
note (i said 7 at the end but looks like between 6 and 7 there is no difference)

**Comment by blackspherefollower** [comment]
Perfect. 3 sounds like the first pattern, so we'll set the step count to 2.

**Comment by Bobafet231** [comment]
oh nice soo now i just need to wait for an update of the repo and also from Intiface right ?

**Comment by blackspherefollower** [comment]
If you're on a desktop platform, you could take the device config JSON file and replace your local copy. On Windows you'd find that in `C:\Users\<username>\AppData\Roaming\com.nonpolynomial\intiface_central\config`

**Comment by Bobafet231** [comment]
oh thank you its only config changes thats cool

**Comment by Bobafet231** [comment]
yep works big thanks, theres only the rotation that is a bit wierd (not really reactive) sometimes when i set the slider to a value nothing happens and when i set it to 0 it never stops i need to lower it manually until it stops
but maybe its just a bug with iniface and using it with games it will be fine i dont know

**Comment by blackspherefollower** [comment]
That's a bit odd, but it's really hard to tell what could cause that. I've ordered one, so hopefully if there's any protocol bugs, I'll be able to find them in a week or so.
