### ISSUE TITLE
Lelo F1S v3 support

### ISSUE THREAD

**Issue by danzohar** [buttplugio/buttplug#649]
Hi there,

The Lelo F1S v3 is currently not supported, I've added "F1SV3" device name in the lelo-f1s-v2 device config json to add the support.

You will find the updated config:
[buttplug-device-config-v3.json](https://github.com/user-attachments/files/16334047/buttplug-device-config-v3.json)

And logs:
[f1sv3.log](https://github.com/user-attachments/files/16334050/f1sv3.log)

There is a crash notification in the logs, I think it happens when I tried to turn it off, I did not press the power button long enough to turn it off instead I think it switched to standalone mode.

Thanks.

**Comment by qdot** [comment]
Wow, thanks!

So, during the time it was yelling about implementing write-with-response, was the toy actually working?

Also cc @blackspherefollower

**Comment by danzohar** [comment]
Hi @qdot and @blackspherefollower 

Yes the device works while yelling about write-with-response.

It's really tricky to be detected, I may turn it off/on several times before seeing it.

I also see this error time to time:
`Device errored while trying to connect: Device type specific error: Btleplug error: NotConnected.`

Here are some logs:
[intiface-central-2024-07-22-22-49-33.log](https://github.com/user-attachments/files/16339847/intiface-central-2024-07-22-22-49-33.log)

**Comment by blackspherefollower** [comment]
Cool. I'll roll that into the next set of updates. The Lelo Enigma Double Sonic also emits the write mode warnings: they're benign, but I'll need to retest the existing Lelo models to change it.

**Comment by danzohar** [comment]
Glad to help, just ask if you need some tests

**Comment by blackspherefollower** [comment]
I've Added the config in the latest protocol PR: 575f1fd3d9a6f22e936d33cc7cbf96fd909516dc

**Comment by blackspherefollower** [comment]
This was fiixed by https://github.com/buttplugio/buttplug/commit/4dfb4f7791f68fb095a91191b2653b1375319c44
