### ISSUE TITLE
Feature request: Database of acceptable "medium" settings for different buttplug models

### ISSUE THREAD

**Issue by sylvieee-iot** [buttplugio/buttplug#653]
I have using been this library with my toys, a Lovense Lush Pink 3 and a Lovense Exomoon Bluetooth Mini Lipstick Vibrator I got form amazon.de

My program defaults to setting the strength to 50, which is ok with the latter but rearranges my guts wit the former. It would be good to have a database that tells me a good, healthy, safe "initial" value for vibrator motor strength.

Thank you for your reading. Much love,
Sylvie.

**Comment by qdot** [comment]
We can't really know that, because each body type is different so we can't really say what "good" is. We have a way for users to set maximum speed values in order to reset where 50% might be, which I think pretty much covers this?
