### ISSUE TITLE
Devices with LinearCmd features before ScalarCmd will trigger index out of bounds errors

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug#668]
If a device is defined to have a LinearCmd feature followed by a ScalarCmd features, sending a ScalarCmd will trigger an index out of bounds error at src\server\device\protocol\actuator_command_manager.rs:231

This was captured in https://nonpolynomial.sentry.io/issues/4643392620/events/fb027d99efc041d9bb8c33b30cca4c19/?project=4505694319476736

It appears the v4 global feature indexing was not accounted for in the actuator_command_manager.rs state manager logic: if a non-ScalarCmd feature precedes a ScalarCmd (or a RotateCmd), the feature index will not match the ScalarCmd states index.

E.g.
feature 0, LinearCmd (not stateful)
feature 1, ScalarCmd -> state array has a size of 1, but the feature index is used to store it's state: state[1] results in the out of bounds error.

**Comment by qdot** [comment]
Do you think this is also #656 ? I'll dupe that against this if so, since this has more detail

**Comment by blackspherefollower** [comment]
Yes, I suspect it is. Sorry, I should really have searched the issues for the error.

**Comment by qdot** [comment]
Nah you're fine, I didn't really know *what* the error was so it was kinda hard to discern. Since this one has details and a fix I'll just dupe the other.
