### ISSUE TITLE
is the model Osci (from Lovense) compatible with buttplug library? 

### ISSUE THREAD

**Issue by mathemagie** [buttplugio/buttplug#67]
i try to control the Osci (https://fr.lovense.com/oscillating-gspot-vibrator
) with the playground : https://playground.buttplug.world/

the sextoy is well connected in web-bluetooth but i have this error message 

"Cannot open device LVS-Osci36: NotFoundError: No Services found in device." 

<img width="436" alt="screen shot 2018-10-30 at 10 41 23" src="https://user-images.githubusercontent.com/180781/47709783-5efdce00-dc31-11e8-91dc-fa76096fbce4.png">

<img width="907" alt="screen shot 2018-10-30 at 10 41 31" src="https://user-images.githubusercontent.com/180781/47709786-64f3af00-dc31-11e8-9167-21356841c84f.png">

thks !

**Comment by qdot** [comment]
Issue moved to [buttplugio/buttplug-js #137](https://github.com/buttplugio/buttplug-js/issues/137) via [**ZenHub**](https://www.zenhub.com/)

**Comment by qdot** [comment]
(Moved because this is specific to Buttplug-js)
