### ISSUE TITLE
Write standard GUI protocol for server CLIs

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#74]
We need a way for the server processes to reflect info back to the new GUI server. We can probably just use pipes and pbuf's for this, but we'll need to figure out what set of messages they'll need to share.

Current list:
- Process Started
- Process Ended
- Log Message
- Client Connected/Disconnected
- Client Name
- Device Connected
- Device Disconnected

**Comment by blackspherefollower** [comment]
It might be useful to add some sort of event collection for the test devices in here too: it'd be a really useful feature both for development and new comers to be able to add the test devices in the same way that the JS project has the simulated devices and visualise their activity on the server GUI.

**Comment by qdot** [comment]
This is more of a Intiface thing than a Buttplug thing now. Closing and reconsidering how this will work there.
