### ISSUE TITLE
Requirements for standard application/server config file

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#75]
We need a standard YAML config file with the following options

- Device Blacklist (devices to ignore)
- Explicit Device Port mappings (serial ports, etc...)
- Automated Check for Updates
- Automated Check for Devices File
- https/http for websocket
- Websocket Server Address / Localhost Only
- Websocket Server Port
- IPC pipe name
- Proxy Server Address
- Proxy Server Port
- Ping timing

**Comment by valuta1995** [comment]
Perhaps a (optional) regex to match for names; hardware addresses.

Why yaml, personal preference?

**Comment by blackspherefollower** [comment]
From the Discord:

qdotToday at 7:51 AM
> (BTW, thinking YAML for the config and device files because comments)
> JSON is handy and all but I'd really like to be able to write comments.

blackspherefollowerToday at 7:53 AM
> Fair point
> I find YAML a little harder to work with, but comments are a huge boon

qdotToday at 7:55 AM
> Agreed on the harder to work with, I've had some real headscratchers with the appveyor/travis configs.
> But I also have a ton of comments in there now to remember why things are the way they are, and when it comes to configs that's so nice to have.

**Comment by qdot** [comment]
> Perhaps a (optional) regex to match for names; hardware addresses.

I'll see about regex, but there's only so much I can do there. We have * operators for WebBluetooth (which we use for things like Lovense's LVS prefix), but that's about it there, so I'm a bit hamstrung on how I can deal with that on multiple platforms at once.

**Comment by qdot** [comment]
Oh and I should also say, this file won't be for listing device configs, that's going to be yet another config file that I'll be making another issue for.

**Comment by qdot** [comment]
Since I'm doing my best to move all application work to intiface, and this is pretty much done there anyways, closing this.
