### ISSUE TITLE
RFP - Remove Major/Minor/Build version from ServerInfo message

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#81]
**Name of Incoming Message, if any:**

ServerInfo

**Message Fields:**

- ServerInfo
  - Already a message, see https://buttplug-spec.docs.buttplug.io/identification.html#requestserverinfo
  - Proposal is to temove MajorVersion/MinorVersion/BuildVersion

**Describe message usage scenario**

These fields don't actually make any sense. I'd originally planned on trying to lockstep server versions but that is so not going to happen.

**Comment by blackspherefollower** [comment]
For backwards compatibility, rather than remove them they could be optional and clients talking v0-1 would cause the message downgrade code to set the values to 0

**Comment by qdot** [comment]
I think I'm fine doing this as optional in the schema. It shouldn't hurt anything.

**Comment by qdot** [comment]
Fixed as optional in dev schema (https://github.com/buttplugio/buttplug-schema/commit/0af6646c8401edc7060741de81e886d084bff75f), will close once that makes it to master.

**Comment by qdot** [comment]
Implemented in v2.
