### ISSUE TITLE
RFP - StepCount Attribute for DeviceAdded/DeviceList

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#91]
**Name of Outgoing Message, if any:**

- DeviceList/DeviceAdded, as part of the Message Attributes section.

**Message Fields:**

- As part of DeviceList/DeviceAdded
  - Attribute: StepCount
    - Type: Array of numbers
    - Description: Number of discrete levels/steps the command can use.

**Describe message usage scenario**

Generic messages currently take a value from 0.0-1.0. However, the client is never told how many steps within this command are valid. One piece of hardware may have 20 vibration levels, while another may have 255. The "StepCount" attribute allows developers receiving the message to scale their generic commands based on the known number of values, versus having to guess in an infinite range.

StepCount can be an array of numbers, as there could be multiple features in a device that take a variable amount of steps (i.e. in a device with 2 vibrators, one may have 10 discrete steps of speed, while the other has 20). 

**Additional context**

JSON Example of a Lovense device being added:

```json
[
  {
    "DeviceAdded": {
      "Id": 0,
      "DeviceName": "TestDevice 1",
      "DeviceIndex": 0,
      "DeviceMessages": {
        "SingleMotorVibrateCmd": {},
        "VibrateCmd": { "FeatureCount": 2, "StepCount": [20, 20] },
        "StopDeviceCmd": {}
      }
    }
  }
]
```

**Comment by blackspherefollower** [comment]
Without #93, this might get messy in the code, but that's a chicken/egg problem

**Comment by blackspherefollower** [comment]
For backwards compatibility, this will need to be stripped off the message for clients using v1

**Comment by qdot** [comment]
Added to beta documentation: https://buttplug-spec-beta.docs.buttplug.io/enumeration.html#message-attributes-for-devicelist-and-deviceadded

**Comment by blackspherefollower** [comment]
Worth noting the introduction in V2 in the doc?

**Comment by qdot** [comment]
Good idea! Should probably build the Changelog directly into the spec.

**Comment by blackspherefollower** [comment]
As noted in the PatternCmd issue, is 0 none or 1. I think in the case of and on/off device, 1 step makes most sense.

**Comment by qdot** [comment]
Yup, should always be 1. Steps of 0 would be "why is this even listed as a supported message". I'll update spec.

**Comment by qdot** [comment]
Implemented in v2.
