### ISSUE TITLE
RFP: RawReadCmd, RawWriteCmd, RawReading (replacements for RawCmd)

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#95]
**Name of Outgoing Message, if any:**

*RawReadCmd* - Read raw data from an endpoint (should return RawReading, Error otherwise)

*RawWriteCmd* - Write raw data to an endpoint (should return Ok, Error otherwise)

**Name of Incoming Message, if any:**

*RawReading* - Returned from RawReadCmd, or emitted when RawSubscribe has been used.

**Message Fields:**

- RawWriteCmd
  - Id, DeviceIndex (as usual for device messages)
  - Endpoint: string - Name of the Endpoint to send raw data to
  - Data: uint8 array - Raw byte string to be sent to Endpoint
  - WriteWithResponse: boolean - True for Bluetooth LE writes that require response.

- RawReadCmd
  - Id, DeviceIndex (as usual for device messages)
  - Endpoint: string - Name of the Endpoint to read raw data from
  - Length: u32 - amount of data to read, 0 for "whatever is in the buffer".
  - Timeout: u32 - time to wait for data (in milliseconds), 0 for "until we get as much data as we asked for"

- RawReading
  - Id, DeviceIndex (as usual for device messages)
  - Endpoint: string - Name of the Endpoint data was received from.
  - Data: uint8 array - Raw byte string received from endpoint.

**Describe message usage scenario**

The Raw message set will mainly be used for development on new hardware, and very rarely for doing things like Firmware updates when required.

Raw messages should be turned off by default, and turning them on should require permissions prompts at minimum.

Endpoints are strings that identify an I/O endpoint on a device. In the reference libraries, these are defined in the device config files.

RawWriteCmd will send a raw byte array to an endpoint.

RawReadCmd will read a raw byte array from an endpoint. User can specify length of read, as well as whether to wait until data is in buffer for read to return.

RawReading is the message that will be returned from either RawCmd or emitted after a successful RawSubscribe.

**Additional context**

This message will solidify the ideas of devices have string-describable endpoints, elevating the idea from the reference implementations to the protocol level. I'm personally ok with this, as it's still a bus-agnostic identifier, so it's not really locking down anything, and this message shouldn't be used by most applications.

That said, the idea of putting a set of volatile messages in the protocol that won't be used by applications is also extremely dicey, so there's also the option of building this as an "extension" that's not part of the main protocol. Doing that seems like it'd be a severe hassle to pull off, though. Mostly just worried that someone will use this to kick devices into bootloader modes or something.

**Comment by blackspherefollower** [comment]
Would RawDataCmd's Return Endpoint read via Read where possible, as opposed to subscribing to Notify before and waiting for the new value after the command? If so, that gives potential access to both read types, even if that's going to be hell to explain in documentation.

**Comment by qdot** [comment]
> Would RawDataCmd's Return Endpoint read via Read where possible, as opposed to subscribing to Notify before and waiting for the new value after the command? If so, that gives potential access to both read types, even if that's going to be hell to explain in documentation.

Yeah that's why we have both RawSubscribe and RawDataCmd + Read. RawDataCmd + Read Endpoint handles serial/usb/bluetooth w/ read, Subscribe handles bluetooth notify.

And yeah, that's gonna be pretty messy, but it's dev messages so we're allowed. :)

**Comment by qdot** [comment]
Ok. Just came back to read this and would now like to concede that the all-in-one RawDataCmd is way too premature-optimization-y, even for just being at the protocol level. Splitting this out to RawDataWriteCmd and RawDataReadCmd, while also keeping subscribe.

**Comment by qdot** [comment]
In beta docs at

https://buttplug-spec-beta.docs.buttplug.io/raw.html

**Comment by qdot** [comment]
Renamed "RawData" to just "Raw". We know it's data.

**Comment by qdot** [comment]
RawSubscribe/RawUnsubscribe are now part of #107, now using SubscribeCmd/UnsubscribeCmd and passing RawReading as the output.

**Comment by qdot** [comment]
Changed "WaitForData" to "Timeout" on read to give us more flexibility.

**Comment by qdot** [comment]
Implemented in v2.
