### ISSUE TITLE
Project Proposal: Crash reporting via Intiface GUI

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug#96]
In the WPF Buttplug Server, crashes were intercepted and optionally reported via Sentry.io, but since the move to the CLI, that functionality has been lost.

Adding the global exception back into the CLI wouldn't be too hard, but given it's supposed to be managed by the Intiface GUI now, having it pop up the permission to report the crash dialog isn't great. Having it prompt on the command-line and having to have Intiface deal with that would be particularly tricky.

A potential solution may be to always write the crash dumps to a directory that Intiface can watch: if a new crash dump is found, Intiface could ask to report it up to Sentry.

**Comment by qdot** [comment]
Closing here, filed on desktop: https://github.com/intiface/intiface-desktop/issues/92
