### ISSUE TITLE
Lovense MAx 2 Connect with no Lovense Special USB Dongle?

### ISSUE THREAD

**Issue by badplay** [buttplugio/buttplug#97]
Hi

is there a hacked way to use the max2 on a windows 10 pc without to bough the expensiv lovense bluetooth dongle???

I dosnt know that i need it on windows so i thinked normal dongle works but it isnt now i cant only get the usb dongle from lovense for 20 dollers :(

**Comment by qdot** [comment]
Just buy a normal Bluetooth Dongle for use with Intiface/Buttplug. We usually recommend https://www.amazon.com/Plugable-Bluetooth-Adapter-Raspberry-Compatible/dp/B009ZIILLI/ref=as_li_ss_tl?ie=UTF8&linkCode=sl1&tag=qdot-20&linkId=11130f024eca91cf48480c71e17df8b0&language=en_US.
