### ISSUE TITLE
Deprecate all Specific Device Messages

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#99]
Deprecate the following message types

- KiirooCmd
- FleshlightLaunchFW12Cmd (This one is gonna be the problem)
- LovenseCmd
- VorzeA10CycloneCmd

None of these are really usable long term, and if we keep making vendor specific messages, we're gonna end up with a huge protocol with a bunch of outdated message types to support. These can be replaced by usages of RawCmd if absolutely needed.

**Comment by blackspherefollower** [comment]
Seems like deprecation here really means, state that they're deprecated and don't use them in new protocol implementations.

For existing implementations, they should probably continue to work, otherwise existing software is going to stop working.

**Comment by qdot** [comment]
Yeah, I think I need to clarify that in the spec. This basically means we can cut them out of the client API for now.

**Comment by blackspherefollower** [comment]
For the FleshlightCmd and Vorze, does cut them out mean annotate as deprecated?

I can see existing apps upgrade to get new functionality, but not having time to rework the existing usage.

**Comment by qdot** [comment]
Yeah this is a tough one. Since we haven't moved to full on major versions yet, this will be a breaking change.

Obviously this means we should move to major versions, but I'm not sure if now is the time for that.

**Comment by qdot** [comment]
What I guess I'm saying is yeah, I suppose I'm fine with annotating deprecated where we can for now, and fully deprecating when we go to major versions.

**Comment by qdot** [comment]
Done in v2. In buttplug-rs, device specific messages still live in v1 support, but are upgraded as possible to generic messages.
